spring:
  application:
    name: phoneshop
  datasource:
    url: jdbc:postgresql://localhost:5432/phone_shop
    username: admin
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    springdoc:
      swagger-ui:
        path: /swagger-ui.html
      api-docs:
        path: /v3/api-docs
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml