spring:
  application:
    name: phoneshop
  datasource:
    url: jdbc:postgresql://localhost:5432/phone_shop
    username: admin
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        check_nullability: true